const WS_CONNECTED = 'orderBook/WS_CONNECTED';
const FETCH_ORDER_BOOK = 'orderBook/FETCH_ORDER_BOOK';
const UPDATE_BIDS = 'orderBook/UPDATE_BIDS';
const UPDATE_ASKS = 'orderBook/UPDATE_ASKS';
const SET_DIFFS = 'orderBook/SET_DIFFS';
const SET_SYMBOL = 'orderBook/SET_SYMBOL';


export {WS_CONNECTED, FETCH_ORDER_BOOK, SET_DIFFS, UPDATE_ASKS, UPDATE_BIDS, SET_SYMBOL};
